# Auto-generated by site-factory. One-shot post-scaffold bootstrap.
# Run from the project root:  ./setup.ps1
$ErrorActionPreference = "Stop"

Write-Host "Installing dependencies..."
npm install

Write-Host "Creating dev database 'orangesmiley' (ignore error if it exists)..."
try { createdb orangesmiley } catch { Write-Host "  createdb skipped/failed - create it manually if needed." }

if (Test-Path .env.example) {
  if (-not (Test-Path .env)) {
    Copy-Item .env.example .env
    Write-Host "Copied .env.example -> .env  (fill in DATABASE_URL etc.)"
  }
}

if (Test-Path data/SECRET-SCAN-FINDINGS.txt) {
  Write-Host ""
  Write-Host "!! Secret scan flagged potential secrets - see data/SECRET-SCAN-FINDINGS.txt" -ForegroundColor Red
  Write-Host "!! Resolve them before committing. Skipping git init/commit." -ForegroundColor Red
} elseif (-not (Test-Path .git)) {
  git init | Out-Null
  git add -A
  git commit -m "scaffold orangesmiley from HalliProjects base" | Out-Null
  Write-Host "Initialized git and committed scaffold."
}

Write-Host ""
Write-Host "Setup complete. Next:  claude   then run /status  (never /strip-base on this repo - CLAUDE.md)"
Write-Host "Dev server (detached): npm run dev:up / dev:down / dev:status"
Write-Host "Tip: in Claude Code, run /hooks to confirm the PostToolUse + Stop hooks are wired."
