-- os_003_sales_guides_d022_pricing — reference copy; the runner applies the entry
-- in server/config/product-migrations/os.js (OS_003_EDITS + guideEdit). D-022
-- (2026-09-26, amends D-001): the seeded sales guides move to the service contract
-- 29/59/89 þ.kr./mán with 2/3/5 verkeiningar, einingaverð 6.000 kr., hosting and
-- in-system AI beyond the included amount at cost + 15 %, and learn the fourth
-- tier Samstarf (price agreed after a free assessment) and when a seller offers
-- that assessment. Build fees 390/580/690 þ.kr. unchanged. Only guides no person
-- has saved (updated_by IS NULL) are touched, and each statement only while its
-- old passage is present and its new one absent. `published` is untouched. All DRÖG.

UPDATE sales_guides SET body = replace(body, 'keyrir í skýinu (þ.e. á netþjónum sem við sjáum um, viðskiptavinurinn þarf engan búnað) og er í boði í þremur þjónustuleiðum.</p>', 'keyrir í skýinu (þ.e. á netþjónum sem við sjáum um, viðskiptavinurinn þarf engan búnað) og er í boði í þremur þjónustuleiðum með föstu verði. Fjórða leiðin, <strong>Samstarf</strong>, er fyrir fyrirtæki sem þurfa kerfi smíðað utan um eigin rekstur: þar er verðið samið eftir ókeypis úttekt (sjá <em>Þrepin þrjú</em>).</p>')
       WHERE slug = 'velkomin-i-soluteymid' AND updated_by IS NULL
         AND position('keyrir í skýinu (þ.e. á netþjónum sem við sjáum um, viðskiptavinurinn þarf engan búnað) og er í boði í þremur þjónustuleiðum.</p>' in body) > 0 AND position('keyrir í skýinu (þ.e. á netþjónum sem við sjáum um, viðskiptavinurinn þarf engan búnað) og er í boði í þremur þjónustuleiðum með föstu verði. Fjórða leiðin, <strong>Samstarf</strong>, er fyrir fyrirtæki sem þurfa kerfi smíðað utan um eigin rekstur: þar er verðið samið eftir ókeypis úttekt (sjá <em>Þrepin þrjú</em>).</p>' in body) = 0;

UPDATE sales_guides SET body = replace(body, '<li><strong>Einingaverð</strong> — fast verð fyrir hverja verkeiningu umfram þær sem fylgja þjónustusamningnum. Upphæðin er ekki ákveðin (DRÖG — Halli staðfestir).</li>', '<li><strong>Einingaverð</strong> — fast verð fyrir hverja verkeiningu umfram þær sem fylgja þjónustusamningnum: 6.000 kr. án VSK (DRÖG — Halli staðfestir).</li>
<li><strong>Samstarf</strong> — fjórða leiðin, fyrir fyrirtæki sem þurfa kerfi smíðað utan um eigin rekstur. Samstarf hefur ekkert listaverð: verðið er samið eftir <em>ókeypis úttekt</em>.</li>
<li><strong>Ókeypis úttekt</strong> — við förum yfir rekstur fyrirtækisins og hvað við leggjum til að smíða fyrir það. Úttektin kostar viðskiptavininn ekkert, og út úr því kemur tilboð í Samstarf.</li>')
       WHERE slug = 'ordalisti' AND updated_by IS NULL
         AND position('<li><strong>Einingaverð</strong> — fast verð fyrir hverja verkeiningu umfram þær sem fylgja þjónustusamningnum. Upphæðin er ekki ákveðin (DRÖG — Halli staðfestir).</li>' in body) > 0 AND position('<li><strong>Einingaverð</strong> — fast verð fyrir hverja verkeiningu umfram þær sem fylgja þjónustusamningnum: 6.000 kr. án VSK (DRÖG — Halli staðfestir).</li>
<li><strong>Samstarf</strong> — fjórða leiðin, fyrir fyrirtæki sem þurfa kerfi smíðað utan um eigin rekstur. Samstarf hefur ekkert listaverð: verðið er samið eftir <em>ókeypis úttekt</em>.</li>
<li><strong>Ókeypis úttekt</strong> — við förum yfir rekstur fyrirtækisins og hvað við leggjum til að smíða fyrir það. Úttektin kostar viðskiptavininn ekkert, og út úr því kemur tilboð í Samstarf.</li>' in body) = 0;

UPDATE sales_guides SET body = replace(body, '<li><strong>Hýsing</strong> — að geyma og keyra vef eða kerfi á netþjóni. Innifalin í þjónustusamningnum.</li>', '<li><strong>Hýsing</strong> — að geyma og keyra vef eða kerfi á netþjóni. Innifalin í þjónustusamningnum, í þeirri stærð sem fylgir þrepinu. Þurfi viðskiptavinurinn meira er það sem umfram er rukkað á kostnaðarverði skýjaþjónustunnar (Azure) að viðbættum 15 %.</li>')
       WHERE slug = 'ordalisti' AND updated_by IS NULL
         AND position('<li><strong>Hýsing</strong> — að geyma og keyra vef eða kerfi á netþjóni. Innifalin í þjónustusamningnum.</li>' in body) > 0 AND position('<li><strong>Hýsing</strong> — að geyma og keyra vef eða kerfi á netþjóni. Innifalin í þjónustusamningnum, í þeirri stærð sem fylgir þrepinu. Þurfi viðskiptavinurinn meira er það sem umfram er rukkað á kostnaðarverði skýjaþjónustunnar (Azure) að viðbættum 15 %.</li>' in body) = 0;

UPDATE sales_guides SET body = replace(body, '<p>Þjónustuleiðirnar þrjár (sjá <em>Þrepin þrjú</em>) eru einfaldlega mismunandi stórir skammtar af þessu sama kerfi — ekki þrjár ólíkar vörur.</p>', '<p>Þjónustuleiðirnar þrjár (sjá <em>Þrepin þrjú</em>) eru einfaldlega mismunandi stórir skammtar af þessu sama kerfi — ekki þrjár ólíkar vörur. Fyrirtæki sem þarf kerfi smíðað utan um eigin rekstur fer í fjórðu leiðina, <strong>Samstarf</strong>: þar er verðið samið eftir ókeypis úttekt.</p>')
       WHERE slug = 'kerfid-i-stuttu-mali' AND updated_by IS NULL
         AND position('<p>Þjónustuleiðirnar þrjár (sjá <em>Þrepin þrjú</em>) eru einfaldlega mismunandi stórir skammtar af þessu sama kerfi — ekki þrjár ólíkar vörur.</p>' in body) > 0 AND position('<p>Þjónustuleiðirnar þrjár (sjá <em>Þrepin þrjú</em>) eru einfaldlega mismunandi stórir skammtar af þessu sama kerfi — ekki þrjár ólíkar vörur. Fyrirtæki sem þarf kerfi smíðað utan um eigin rekstur fer í fjórðu leiðina, <strong>Samstarf</strong>: þar er verðið samið eftir ókeypis úttekt.</p>' in body) = 0;

UPDATE sales_guides SET body = replace(body, 'Nefndu þrepið sem þér sýnist passa og af hverju. Ef verð ber á góma:', 'Nefndu þrepið sem þér sýnist passa og af hverju — eða, ef reksturinn þarf kerfi smíðað utan um sig, bjóddu ókeypis úttekt í stað þreps (sjá <em>Þrepin þrjú</em>, kaflann um Samstarf). Ef verð ber á góma:')
       WHERE slug = 'fyrsta-samtalid' AND updated_by IS NULL
         AND position('Nefndu þrepið sem þér sýnist passa og af hverju. Ef verð ber á góma:' in body) > 0 AND position('Nefndu þrepið sem þér sýnist passa og af hverju — eða, ef reksturinn þarf kerfi smíðað utan um sig, bjóddu ókeypis úttekt í stað þreps (sjá <em>Þrepin þrjú</em>, kaflann um Samstarf). Ef verð ber á góma:' in body) = 0;

UPDATE sales_guides SET title = replace(title, 'Þrepin þrjú og hverjum þau henta', 'Þrepin þrjú, Samstarf og hverjum þau henta')
       WHERE slug = 'threpin-thrju' AND updated_by IS NULL
         AND position('Þrepin þrjú og hverjum þau henta' in title) > 0 AND position('Þrepin þrjú, Samstarf og hverjum þau henta' in title) = 0;

UPDATE sales_guides SET summary = replace(summary, 'Vefur, Verslun og Rekstur: uppsetningargjald 390 / 580 / 690 þ.kr. og þjónustusamningur 19 / 29 / 39 þ.kr./mán með 5 / 10 / 20 verkeiningum á mánuði — öll verð DRÖG þar til Halli staðfestir, öll án VSK. Aldrei tímagjald. Hér lærirðu verðmódelið, hvað verkeining er og hvernig þú parar fyrirtæki við rétt þrep.', 'Vefur, Verslun og Rekstur: uppsetningargjald 390 / 580 / 690 þ.kr. og þjónustusamningur 29 / 59 / 89 þ.kr./mán með 2 / 3 / 5 verkeiningum á mánuði, einingaverð 6.000 kr. umfram það — öll verð DRÖG þar til Halli staðfestir, öll án VSK. Fjórða leiðin, Samstarf, hefur ekkert listaverð: verðið er samið eftir ókeypis úttekt. Aldrei tímagjald. Hér lærirðu verðmódelið, hvað verkeining er, hvernig þú parar fyrirtæki við rétt þrep og hvenær þú býður ókeypis úttekt í staðinn.')
       WHERE slug = 'threpin-thrju' AND updated_by IS NULL
         AND position('Vefur, Verslun og Rekstur: uppsetningargjald 390 / 580 / 690 þ.kr. og þjónustusamningur 19 / 29 / 39 þ.kr./mán með 5 / 10 / 20 verkeiningum á mánuði — öll verð DRÖG þar til Halli staðfestir, öll án VSK. Aldrei tímagjald. Hér lærirðu verðmódelið, hvað verkeining er og hvernig þú parar fyrirtæki við rétt þrep.' in summary) > 0 AND position('Vefur, Verslun og Rekstur: uppsetningargjald 390 / 580 / 690 þ.kr. og þjónustusamningur 29 / 59 / 89 þ.kr./mán með 2 / 3 / 5 verkeiningum á mánuði, einingaverð 6.000 kr. umfram það — öll verð DRÖG þar til Halli staðfestir, öll án VSK. Fjórða leiðin, Samstarf, hefur ekkert listaverð: verðið er samið eftir ókeypis úttekt. Aldrei tímagjald. Hér lærirðu verðmódelið, hvað verkeining er, hvernig þú parar fyrirtæki við rétt þrep og hvenær þú býður ókeypis úttekt í staðinn.' in summary) = 0;

UPDATE sales_guides SET body = replace(body, '<p>Rekstrarkerfið er selt í þremur þjónustuleiðum — þrepum. Þau eru ekki þrjár vörur heldur mismunandi stórir skammtar af sama kerfinu; viðskiptavinur getur alltaf fært sig upp síðar.', '<p>Rekstrarkerfið er selt í þremur þjónustuleiðum með föstu verði — þrepum. Þau eru ekki þrjár vörur heldur mismunandi stórir skammtar af sama kerfinu; viðskiptavinur getur alltaf fært sig upp síðar. Fjórða leiðin, <strong>Samstarf</strong>, er fyrir fyrirtæki sem þurfa kerfi smíðað utan um eigin rekstur; hún hefur ekkert listaverð og henni er lýst neðst í þessari leið.')
       WHERE slug = 'threpin-thrju' AND updated_by IS NULL
         AND position('<p>Rekstrarkerfið er selt í þremur þjónustuleiðum — þrepum. Þau eru ekki þrjár vörur heldur mismunandi stórir skammtar af sama kerfinu; viðskiptavinur getur alltaf fært sig upp síðar.' in body) > 0 AND position('<p>Rekstrarkerfið er selt í þremur þjónustuleiðum með föstu verði — þrepum. Þau eru ekki þrjár vörur heldur mismunandi stórir skammtar af sama kerfinu; viðskiptavinur getur alltaf fært sig upp síðar. Fjórða leiðin, <strong>Samstarf</strong>, er fyrir fyrirtæki sem þurfa kerfi smíðað utan um eigin rekstur; hún hefur ekkert listaverð og henni er lýst neðst í þessari leið.' in body) = 0;

UPDATE sales_guides SET body = replace(body, '<h2>Vefur — 390 þ.kr. uppsetning + 19 þ.kr./mán með 5 verkeiningum (DRÖG)</h2>', '<h2>Vefur — 390 þ.kr. uppsetning + 29 þ.kr./mán með 2 verkeiningum (DRÖG)</h2>')
       WHERE slug = 'threpin-thrju' AND updated_by IS NULL
         AND position('<h2>Vefur — 390 þ.kr. uppsetning + 19 þ.kr./mán með 5 verkeiningum (DRÖG)</h2>' in body) > 0 AND position('<h2>Vefur — 390 þ.kr. uppsetning + 29 þ.kr./mán með 2 verkeiningum (DRÖG)</h2>' in body) = 0;

UPDATE sales_guides SET body = replace(body, '<h2>Verslun — 580 þ.kr. uppsetning + 29 þ.kr./mán með 10 verkeiningum (DRÖG)</h2>', '<h2>Verslun — 580 þ.kr. uppsetning + 59 þ.kr./mán með 3 verkeiningum (DRÖG)</h2>')
       WHERE slug = 'threpin-thrju' AND updated_by IS NULL
         AND position('<h2>Verslun — 580 þ.kr. uppsetning + 29 þ.kr./mán með 10 verkeiningum (DRÖG)</h2>' in body) > 0 AND position('<h2>Verslun — 580 þ.kr. uppsetning + 59 þ.kr./mán með 3 verkeiningum (DRÖG)</h2>' in body) = 0;

UPDATE sales_guides SET body = replace(body, '<h2>Rekstur — 690 þ.kr. uppsetning + 39 þ.kr./mán með 20 verkeiningum (DRÖG)</h2>', '<h2>Rekstur — 690 þ.kr. uppsetning + 89 þ.kr./mán með 5 verkeiningum (DRÖG)</h2>')
       WHERE slug = 'threpin-thrju' AND updated_by IS NULL
         AND position('<h2>Rekstur — 690 þ.kr. uppsetning + 39 þ.kr./mán með 20 verkeiningum (DRÖG)</h2>' in body) > 0 AND position('<h2>Rekstur — 690 þ.kr. uppsetning + 89 þ.kr./mán með 5 verkeiningum (DRÖG)</h2>' in body) = 0;

UPDATE sales_guides SET body = replace(body, '<li><strong>Þjónustusamningur</strong> — fylgir öllum þrepum, enginn kaupir kerfið án hans: 19 / 29 / 39 þ.kr. á mánuði. Hann innifelur hýsingu, vöktun, öryggisuppfærslur og <strong>5 / 10 / 20 verkeiningar á mánuði</strong> fyrir breytingar og sérsmíði. Hann er rukkaður mánaðarlega fyrir fram, frá þeim mánuði sem kerfið fer í loftið.</li>', '<li><strong>Þjónustusamningur</strong> — fylgir öllum þrepum, enginn kaupir kerfið án hans: 29 / 59 / 89 þ.kr. á mánuði. Hann innifelur hýsingu, vöktun, öryggisuppfærslur og <strong>2 / 3 / 5 verkeiningar á mánuði</strong> fyrir breytingar og sérsmíði. Hann er rukkaður mánaðarlega fyrir fram, frá þeim mánuði sem kerfið fer í loftið.</li>
<li><strong>Hýsing umfram þrepið</strong> — hverju þrepi fylgir hýsing í ákveðinni stærð. Þurfi viðskiptavinurinn meira, t.d. fast prófunarumhverfi eða stærri gagnagrunn, er það sem umfram er rukkað á kostnaðarverði Azure að viðbættum 15 %. Lofaðu aldrei aukahýsingu innifalinni.</li>
<li><strong>Gervigreind í kerfinu</strong> — gervigreind sem vinnur inni í kerfi viðskiptavinarins, t.d. við innlestur pantana, er innifalin upp að 2.000 kr. á mánuði. Umfram það er hún rukkuð á kostnaðarverði að viðbættum 15 %.</li>')
       WHERE slug = 'threpin-thrju' AND updated_by IS NULL
         AND position('<li><strong>Þjónustusamningur</strong> — fylgir öllum þrepum, enginn kaupir kerfið án hans: 19 / 29 / 39 þ.kr. á mánuði. Hann innifelur hýsingu, vöktun, öryggisuppfærslur og <strong>5 / 10 / 20 verkeiningar á mánuði</strong> fyrir breytingar og sérsmíði. Hann er rukkaður mánaðarlega fyrir fram, frá þeim mánuði sem kerfið fer í loftið.</li>' in body) > 0 AND position('<li><strong>Þjónustusamningur</strong> — fylgir öllum þrepum, enginn kaupir kerfið án hans: 29 / 59 / 89 þ.kr. á mánuði. Hann innifelur hýsingu, vöktun, öryggisuppfærslur og <strong>2 / 3 / 5 verkeiningar á mánuði</strong> fyrir breytingar og sérsmíði. Hann er rukkaður mánaðarlega fyrir fram, frá þeim mánuði sem kerfið fer í loftið.</li>
<li><strong>Hýsing umfram þrepið</strong> — hverju þrepi fylgir hýsing í ákveðinni stærð. Þurfi viðskiptavinurinn meira, t.d. fast prófunarumhverfi eða stærri gagnagrunn, er það sem umfram er rukkað á kostnaðarverði Azure að viðbættum 15 %. Lofaðu aldrei aukahýsingu innifalinni.</li>
<li><strong>Gervigreind í kerfinu</strong> — gervigreind sem vinnur inni í kerfi viðskiptavinarins, t.d. við innlestur pantana, er innifalin upp að 2.000 kr. á mánuði. Umfram það er hún rukkuð á kostnaðarverði að viðbættum 15 %.</li>' in body) = 0;

UPDATE sales_guides SET body = replace(body, '<p>Til að gera þetta áþreifanlegt: 5 einingar í Vef duga fyrir fimm litlum verkum eða einu meðalstóru á mánuði; 20 einingar í Rekstri duga fyrir einu stóru verki eða fjórum meðalstórum.</p>', '<p>Til að gera þetta áþreifanlegt: 2 einingar í Vef duga fyrir tveimur litlum verkum á mánuði; 5 einingar í Rekstri duga fyrir fimm litlum verkum eða einu meðalstóru. Stórt verk (20 einingar) er stærra en mánaðarskammtur nokkurs þreps, svo það sem umfram er greiðist á einingaverði — og viðskiptavinurinn sér upphæðina áður en hann samþykkir verkið.</p>')
       WHERE slug = 'threpin-thrju' AND updated_by IS NULL
         AND position('<p>Til að gera þetta áþreifanlegt: 5 einingar í Vef duga fyrir fimm litlum verkum eða einu meðalstóru á mánuði; 20 einingar í Rekstri duga fyrir einu stóru verki eða fjórum meðalstórum.</p>' in body) > 0 AND position('<p>Til að gera þetta áþreifanlegt: 2 einingar í Vef duga fyrir tveimur litlum verkum á mánuði; 5 einingar í Rekstri duga fyrir fimm litlum verkum eða einu meðalstóru. Stórt verk (20 einingar) er stærra en mánaðarskammtur nokkurs þreps, svo það sem umfram er greiðist á einingaverði — og viðskiptavinurinn sér upphæðina áður en hann samþykkir verkið.</p>' in body) = 0;

UPDATE sales_guides SET body = replace(body, 'fyrir það sem umfram er — og fær verðið alltaf gefið upp áður en verkið hefst. Upphæð einingaverðsins er ekki ákveðin: DRÖG — Halli staðfestir. Nefndu enga tölu.</li>', 'fyrir það sem umfram er: <strong>6.000 kr. á einingu án VSK</strong> (DRÖG — Halli staðfestir). Hann fær upphæðina alltaf gefna upp áður en verkið hefst.</li>')
       WHERE slug = 'threpin-thrju' AND updated_by IS NULL
         AND position('fyrir það sem umfram er — og fær verðið alltaf gefið upp áður en verkið hefst. Upphæð einingaverðsins er ekki ákveðin: DRÖG — Halli staðfestir. Nefndu enga tölu.</li>' in body) > 0 AND position('fyrir það sem umfram er: <strong>6.000 kr. á einingu án VSK</strong> (DRÖG — Halli staðfestir). Hann fær upphæðina alltaf gefna upp áður en verkið hefst.</li>' in body) = 0;

UPDATE sales_guides SET body = replace(body, '<p>Einföld regla: <strong>engin vefverslun → Vefur; vefverslun eða búð → Verslun; vill líka losna við sérstakt bókhaldskerfi → Rekstur.</strong> Ef þú ert í vafa, veldu lægra þrepið — það er auðvelt að færa sig upp og enginn upplifir sig plataðan. Hvað það kostar að færa sig upp um þrep síðar er ekki ákveðið: DRÖG — Halli staðfestir.</p>', '<p>Einföld regla: <strong>engin vefverslun → Vefur; vefverslun eða búð → Verslun; vill líka losna við sérstakt bókhaldskerfi → Rekstur; þarf kerfi smíðað utan um eigin rekstur → Samstarf.</strong> Ef þú ert í vafa milli tveggja þrepa, veldu lægra þrepið — það er auðvelt að færa sig upp og enginn upplifir sig plataðan. Hvað það kostar að færa sig upp um þrep síðar er ekki ákveðið: DRÖG — Halli staðfestir. Ef þú ert í vafa um hvort nokkurt þrep passi, bjóddu ókeypis úttekt (sjá hér að neðan).</p>
<h2>Samstarf — fjórða leiðin, verð eftir ókeypis úttekt (DRÖG)</h2>
<p><em>Fyrir fyrirtæki sem þurfa kerfi smíðað utan um eigin rekstur.</em></p>
<p>Sum fyrirtæki passa ekki í neitt þrepanna. Þau vantar ekki stærri skammt af sama kerfinu heldur kerfi sem er smíðað utan um verklagið þeirra: sérstaka vöruflokka og verðlagningu, tengingar við kerfi birgja og viðskiptavina, ferla sem ekkert staðlað kerfi kann. Fyrsti viðskiptavinurinn okkar er einmitt slíkt fyrirtæki. Fyrir þau er <strong>Samstarf</strong>.</p>
<p>Samstarf hefur <strong>ekkert listaverð</strong>. Verðið er samið eftir <strong>ókeypis úttekt</strong>: við förum yfir rekstur fyrirtækisins og hvað við leggjum til að smíða fyrir það, og út úr því kemur tilboð sem Halli sendir. Úttektin kostar viðskiptavininn ekkert. Hvernig samningurinn er byggður upp — uppsetning, mánaðargjald, verkeiningar — kemur fram í tilboðinu, ekki frá þér.</p>
<h2>Hvenær þú býður ókeypis úttekt í stað þreps</h2>
<p>Bjóddu ókeypis úttekt, og nefndu ekkert verð, þegar þú heyrir eitthvað af þessu:</p>
<ul>
<li>Reksturinn byggist á verklagi sem staðlað kerfi styður ekki — „við gerum þetta öðruvísi en allir aðrir“.</li>
<li>Kerfið þarf að tala við mörg önnur kerfi: birgja, heildsala, bókhald, sérhæfðan búnað.</li>
<li>Sérþarfirnar eru margar eða stórar strax í upphafi — ekki ein eða tvær sérsniðnar einingar heldur mörg stór verk.</li>
<li>Fyrirtækið er á leið af eldra kerfi sem hefur verið lagað að því árum saman, og gögnin eða ferlarnir eru flóknir.</li>
<li>Þú getur ekki sagt með vissu hvaða þrep passar, jafnvel eftir fyrsta samtalið.</li>
</ul>
<p>Þá segirðu: <em>„Það sem þið lýsið þarf að smíða utan um ykkar rekstur. Við bjóðum ókeypis úttekt: við förum yfir reksturinn og hvað við myndum smíða, og þið fáið tilboð út frá því. Úttektin kostar ykkur ekkert.“</em> Skráðu það sem þú heyrðir eins og fyrir tilboð (sjá <em>Tilboðsferlið</em>) og láttu Halla vita. Þú framkvæmir ekki úttektina sjálf(ur) og nefnir aldrei verð í Samstarfi, ekki heldur „svona í kringum“. Nefndu heldur aldrei fyrsta viðskiptavininn á nafn eða tölur úr því verkefni.</p>')
       WHERE slug = 'threpin-thrju' AND updated_by IS NULL
         AND position('<p>Einföld regla: <strong>engin vefverslun → Vefur; vefverslun eða búð → Verslun; vill líka losna við sérstakt bókhaldskerfi → Rekstur.</strong> Ef þú ert í vafa, veldu lægra þrepið — það er auðvelt að færa sig upp og enginn upplifir sig plataðan. Hvað það kostar að færa sig upp um þrep síðar er ekki ákveðið: DRÖG — Halli staðfestir.</p>' in body) > 0 AND position('<p>Einföld regla: <strong>engin vefverslun → Vefur; vefverslun eða búð → Verslun; vill líka losna við sérstakt bókhaldskerfi → Rekstur; þarf kerfi smíðað utan um eigin rekstur → Samstarf.</strong> Ef þú ert í vafa milli tveggja þrepa, veldu lægra þrepið — það er auðvelt að færa sig upp og enginn upplifir sig plataðan. Hvað það kostar að færa sig upp um þrep síðar er ekki ákveðið: DRÖG — Halli staðfestir. Ef þú ert í vafa um hvort nokkurt þrep passi, bjóddu ókeypis úttekt (sjá hér að neðan).</p>
<h2>Samstarf — fjórða leiðin, verð eftir ókeypis úttekt (DRÖG)</h2>
<p><em>Fyrir fyrirtæki sem þurfa kerfi smíðað utan um eigin rekstur.</em></p>
<p>Sum fyrirtæki passa ekki í neitt þrepanna. Þau vantar ekki stærri skammt af sama kerfinu heldur kerfi sem er smíðað utan um verklagið þeirra: sérstaka vöruflokka og verðlagningu, tengingar við kerfi birgja og viðskiptavina, ferla sem ekkert staðlað kerfi kann. Fyrsti viðskiptavinurinn okkar er einmitt slíkt fyrirtæki. Fyrir þau er <strong>Samstarf</strong>.</p>
<p>Samstarf hefur <strong>ekkert listaverð</strong>. Verðið er samið eftir <strong>ókeypis úttekt</strong>: við förum yfir rekstur fyrirtækisins og hvað við leggjum til að smíða fyrir það, og út úr því kemur tilboð sem Halli sendir. Úttektin kostar viðskiptavininn ekkert. Hvernig samningurinn er byggður upp — uppsetning, mánaðargjald, verkeiningar — kemur fram í tilboðinu, ekki frá þér.</p>
<h2>Hvenær þú býður ókeypis úttekt í stað þreps</h2>
<p>Bjóddu ókeypis úttekt, og nefndu ekkert verð, þegar þú heyrir eitthvað af þessu:</p>
<ul>
<li>Reksturinn byggist á verklagi sem staðlað kerfi styður ekki — „við gerum þetta öðruvísi en allir aðrir“.</li>
<li>Kerfið þarf að tala við mörg önnur kerfi: birgja, heildsala, bókhald, sérhæfðan búnað.</li>
<li>Sérþarfirnar eru margar eða stórar strax í upphafi — ekki ein eða tvær sérsniðnar einingar heldur mörg stór verk.</li>
<li>Fyrirtækið er á leið af eldra kerfi sem hefur verið lagað að því árum saman, og gögnin eða ferlarnir eru flóknir.</li>
<li>Þú getur ekki sagt með vissu hvaða þrep passar, jafnvel eftir fyrsta samtalið.</li>
</ul>
<p>Þá segirðu: <em>„Það sem þið lýsið þarf að smíða utan um ykkar rekstur. Við bjóðum ókeypis úttekt: við förum yfir reksturinn og hvað við myndum smíða, og þið fáið tilboð út frá því. Úttektin kostar ykkur ekkert.“</em> Skráðu það sem þú heyrðir eins og fyrir tilboð (sjá <em>Tilboðsferlið</em>) og láttu Halla vita. Þú framkvæmir ekki úttektina sjálf(ur) og nefnir aldrei verð í Samstarfi, ekki heldur „svona í kringum“. Nefndu heldur aldrei fyrsta viðskiptavininn á nafn eða tölur úr því verkefni.</p>' in body) = 0;

UPDATE sales_guides SET summary = replace(summary, 'hvað bætist við í Verslun og hvað er aðeins í Rekstri. Þetta er heimildin', 'hvað bætist við í Verslun og hvað er aðeins í Rekstri. Samstarf er utan töflunnar: þar ræður ókeypis úttektin. Þetta er heimildin')
       WHERE slug = 'hvad-er-i-hverju-threpi' AND updated_by IS NULL
         AND position('hvað bætist við í Verslun og hvað er aðeins í Rekstri. Þetta er heimildin' in summary) > 0 AND position('hvað bætist við í Verslun og hvað er aðeins í Rekstri. Samstarf er utan töflunnar: þar ræður ókeypis úttektin. Þetta er heimildin' in summary) = 0;

UPDATE sales_guides SET body = replace(body, 'Vefur 390 þ.kr. uppsetning + 19 þ.kr./mán með 5 verkeiningum, Verslun 580 þ.kr. + 29 þ.kr./mán með 10, Rekstur 690 þ.kr. + 39 þ.kr./mán með 20. Hvert þrep inniheldur allt úr þrepinu á undan.</p>', 'Vefur 390 þ.kr. uppsetning + 29 þ.kr./mán með 2 verkeiningum, Verslun 580 þ.kr. + 59 þ.kr./mán með 3, Rekstur 690 þ.kr. + 89 þ.kr./mán með 5; einingaverð umfram það 6.000 kr. Hvert þrep inniheldur allt úr þrepinu á undan. Samstarf, fjórða leiðin, er ekki í töflunni: þar er kerfið smíðað utan um rekstur viðskiptavinarins og innihaldið ákveðið eftir ókeypis úttekt.</p>')
       WHERE slug = 'hvad-er-i-hverju-threpi' AND updated_by IS NULL
         AND position('Vefur 390 þ.kr. uppsetning + 19 þ.kr./mán með 5 verkeiningum, Verslun 580 þ.kr. + 29 þ.kr./mán með 10, Rekstur 690 þ.kr. + 39 þ.kr./mán með 20. Hvert þrep inniheldur allt úr þrepinu á undan.</p>' in body) > 0 AND position('Vefur 390 þ.kr. uppsetning + 29 þ.kr./mán með 2 verkeiningum, Verslun 580 þ.kr. + 59 þ.kr./mán með 3, Rekstur 690 þ.kr. + 89 þ.kr./mán með 5; einingaverð umfram það 6.000 kr. Hvert þrep inniheldur allt úr þrepinu á undan. Samstarf, fjórða leiðin, er ekki í töflunni: þar er kerfið smíðað utan um rekstur viðskiptavinarins og innihaldið ákveðið eftir ókeypis úttekt.</p>' in body) = 0;

UPDATE sales_guides SET body = replace(body, '(5, 10 eða 20 á mánuði eftir þrepi)', '(2, 3 eða 5 á mánuði eftir þrepi)')
       WHERE slug = 'hvad-er-i-hverju-threpi' AND updated_by IS NULL
         AND position('(5, 10 eða 20 á mánuði eftir þrepi)' in body) > 0 AND position('(2, 3 eða 5 á mánuði eftir þrepi)' in body) = 0;

UPDATE sales_guides SET body = replace(body, '<p>Í öllum þrepum er líka innifalið það sem fylgir þjónustusamningnum sjálfum: hýsing í skýinu, vöktun og öryggisuppfærslur — viðskiptavinurinn kaupir aldrei neitt af þessu sérstaklega.</p>', '<p>Í öllum þrepum er líka innifalið það sem fylgir þjónustusamningnum sjálfum: hýsing í skýinu í þeirri stærð sem fylgir þrepinu, vöktun, öryggisuppfærslur og gervigreind inni í kerfinu upp að 2.000 kr. á mánuði. Aðeins það sem fer umfram — meiri hýsing en þrepinu fylgir, eða gervigreind yfir 2.000 kr. á mánuði — er rukkað sérstaklega, á kostnaðarverði að viðbættum 15 %.</p>')
       WHERE slug = 'hvad-er-i-hverju-threpi' AND updated_by IS NULL
         AND position('<p>Í öllum þrepum er líka innifalið það sem fylgir þjónustusamningnum sjálfum: hýsing í skýinu, vöktun og öryggisuppfærslur — viðskiptavinurinn kaupir aldrei neitt af þessu sérstaklega.</p>' in body) > 0 AND position('<p>Í öllum þrepum er líka innifalið það sem fylgir þjónustusamningnum sjálfum: hýsing í skýinu í þeirri stærð sem fylgir þrepinu, vöktun, öryggisuppfærslur og gervigreind inni í kerfinu upp að 2.000 kr. á mánuði. Aðeins það sem fer umfram — meiri hýsing en þrepinu fylgir, eða gervigreind yfir 2.000 kr. á mánuði — er rukkað sérstaklega, á kostnaðarverði að viðbættum 15 %.</p>' in body) = 0;

UPDATE sales_guides SET body = replace(body, '<li><strong>Uppsetningargjald</strong> er fast verð eftir þrepi (390 / 580 / 690 þ.kr., DRÖG) og <strong>þjónustusamningur</strong> fylgir öllum þrepum.</li>', '<li><strong>Uppsetningargjald</strong> er fast verð eftir þrepi (390 / 580 / 690 þ.kr., DRÖG) og <strong>þjónustusamningur</strong> fylgir öllum þrepum.</li>
<li><strong>Samstarf</strong> er utan þrepanna: hvað er smíðað og hvað það kostar ræðst af ókeypis úttekt (sjá <em>Þrepin þrjú</em>). Lofaðu engum eiginleika í Samstarfi fyrr en úttektin liggur fyrir.</li>')
       WHERE slug = 'hvad-er-i-hverju-threpi' AND updated_by IS NULL
         AND position('<li><strong>Uppsetningargjald</strong> er fast verð eftir þrepi (390 / 580 / 690 þ.kr., DRÖG) og <strong>þjónustusamningur</strong> fylgir öllum þrepum.</li>' in body) > 0 AND position('<li><strong>Uppsetningargjald</strong> er fast verð eftir þrepi (390 / 580 / 690 þ.kr., DRÖG) og <strong>þjónustusamningur</strong> fylgir öllum þrepum.</li>
<li><strong>Samstarf</strong> er utan þrepanna: hvað er smíðað og hvað það kostar ræðst af ókeypis úttekt (sjá <em>Þrepin þrjú</em>). Lofaðu engum eiginleika í Samstarfi fyrr en úttektin liggur fyrir.</li>' in body) = 0;

UPDATE sales_guides SET body = replace(body, '<li><strong>Líklegt þrep:</strong> Vefur, Verslun eða Rekstur, með rökstuðningi í einni setningu.</li>', '<li><strong>Líklegt þrep:</strong> Vefur, Verslun eða Rekstur, með rökstuðningi í einni setningu — eða <strong>Samstarf</strong>, ef reksturinn þarf kerfi smíðað utan um sig (sjá <em>Þrepin þrjú</em>). Þá er næsta skref ókeypis úttekt, ekki tilboð beint.</li>')
       WHERE slug = 'tilbodsferlid' AND updated_by IS NULL
         AND position('<li><strong>Líklegt þrep:</strong> Vefur, Verslun eða Rekstur, með rökstuðningi í einni setningu.</li>' in body) > 0 AND position('<li><strong>Líklegt þrep:</strong> Vefur, Verslun eða Rekstur, með rökstuðningi í einni setningu — eða <strong>Samstarf</strong>, ef reksturinn þarf kerfi smíðað utan um sig (sjá <em>Þrepin þrjú</em>). Þá er næsta skref ókeypis úttekt, ekki tilboð beint.</li>' in body) = 0;

UPDATE sales_guides SET body = replace(body, '<li>Uppsetningargjaldið og þjónustusamningurinn: mánaðargjaldið og hve margar verkeiningar fylgja, öll verð án VSK.', '<li>Uppsetningargjaldið og þjónustusamningurinn: mánaðargjaldið, hve margar verkeiningar fylgja og einingaverðið umfram þær, öll verð án VSK. Þurfi viðskiptavinurinn meiri hýsingu en þrepinu fylgir kemur hún fram sér, á kostnaðarverði að viðbættum 15 %.')
       WHERE slug = 'tilbodsferlid' AND updated_by IS NULL
         AND position('<li>Uppsetningargjaldið og þjónustusamningurinn: mánaðargjaldið og hve margar verkeiningar fylgja, öll verð án VSK.' in body) > 0 AND position('<li>Uppsetningargjaldið og þjónustusamningurinn: mánaðargjaldið, hve margar verkeiningar fylgja og einingaverðið umfram þær, öll verð án VSK. Þurfi viðskiptavinurinn meiri hýsingu en þrepinu fylgir kemur hún fram sér, á kostnaðarverði að viðbættum 15 %.' in body) = 0;

UPDATE sales_guides SET body = replace(body, '<li>Næstu skref: hvað gerist ef tilboðinu er tekið.</li>
</ol>', '<li>Næstu skref: hvað gerist ef tilboðinu er tekið.</li>
</ol>
<p><strong>Í Samstarfi kemur ókeypis úttektin á undan tilboðinu.</strong> Við förum yfir reksturinn með viðskiptavininum og hvað við leggjum til að smíða, og tilboðið byggist á úttektinni. Þú safnar sömu upplýsingum og í skrefi 1 — þær eru grunnurinn að úttektinni — en nefnir ekkert verð, hvorki fyrir úttektina (hún er ókeypis) né fyrir samstarfið sjálft.</p>')
       WHERE slug = 'tilbodsferlid' AND updated_by IS NULL
         AND position('<li>Næstu skref: hvað gerist ef tilboðinu er tekið.</li>
</ol>' in body) > 0 AND position('<li>Næstu skref: hvað gerist ef tilboðinu er tekið.</li>
</ol>
<p><strong>Í Samstarfi kemur ókeypis úttektin á undan tilboðinu.</strong> Við förum yfir reksturinn með viðskiptavininum og hvað við leggjum til að smíða, og tilboðið byggist á úttektinni. Þú safnar sömu upplýsingum og í skrefi 1 — þær eru grunnurinn að úttektinni — en nefnir ekkert verð, hvorki fyrir úttektina (hún er ókeypis) né fyrir samstarfið sjálft.</p>' in body) = 0;

UPDATE sales_guides SET body = replace(body, 'þjónustusamningur 19 / 29 / 39 þ.kr./mán með 5 / 10 / 20 verkeiningum — eru', 'þjónustusamningur 29 / 59 / 89 þ.kr./mán með 2 / 3 / 5 verkeiningum og einingaverð 6.000 kr. — eru')
       WHERE slug = 'hvad-thu-lofar-aldrei' AND updated_by IS NULL
         AND position('þjónustusamningur 19 / 29 / 39 þ.kr./mán með 5 / 10 / 20 verkeiningum — eru' in body) > 0 AND position('þjónustusamningur 29 / 59 / 89 þ.kr./mán með 2 / 3 / 5 verkeiningum og einingaverð 6.000 kr. — eru' in body) = 0;

UPDATE sales_guides SET body = replace(body, '<li>Einingaverðið, það sem greitt er fyrir verkeiningar umfram samninginn, er ekki ákveðið — þú nefnir enga tölu. Hvort ónotaðar einingar flytjist milli mánaða er heldur ekki ákveðið — þú lofar engu um það.</li>', '<li>Hvort ónotaðar einingar flytjist milli mánaða er ekki ákveðið — þú lofar engu um það.</li>
<li><strong>Samstarf hefur ekkert verð fyrr en eftir ókeypis úttektina.</strong> Þú nefnir enga tölu, ekki heldur „svona í kringum“, og lofar hvorki hvað verður smíðað né hvenær.</li>')
       WHERE slug = 'hvad-thu-lofar-aldrei' AND updated_by IS NULL
         AND position('<li>Einingaverðið, það sem greitt er fyrir verkeiningar umfram samninginn, er ekki ákveðið — þú nefnir enga tölu. Hvort ónotaðar einingar flytjist milli mánaða er heldur ekki ákveðið — þú lofar engu um það.</li>' in body) > 0 AND position('<li>Hvort ónotaðar einingar flytjist milli mánaða er ekki ákveðið — þú lofar engu um það.</li>
<li><strong>Samstarf hefur ekkert verð fyrr en eftir ókeypis úttektina.</strong> Þú nefnir enga tölu, ekki heldur „svona í kringum“, og lofar hvorki hvað verður smíðað né hvenær.</li>' in body) = 0;
